name: Update README with latest projects

on:
  schedule:
    - cron: '0 8 * * *'   # täglich 08:00 UTC
  workflow_dispatch:       # manueller Start möglich

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch recent repos
        id: repos
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = 'laurinhuebner';
            const { data: repos } = await github.rest.repos.listForUser({
              username,
              sort: 'updated',
              direction: 'desc',
              per_page: 5
            });
            const list = repos
              .filter(r => !r.fork && !r.private)
              .map(r => `- [**${r.name}**](${r.html_url})  \n  *${r.description?.replace(/\r?\n/g,' ').trim() || "Keine Beschreibung"}*`)
              .join("\n") || "*Noch keine öffentlichen Repos*";
            core.setOutput('projects', list);

      - name: Update README section (RECENT_PROJECTS)
        uses: actions/github-script@v7
        env:
          PROJECTS: ${{ steps.repos.outputs.projects }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = 'README.md';
            const start = '<!-- RECENT_PROJECTS_START -->';
            const end   = '<!-- RECENT_PROJECTS_END -->';
            if (!fs.existsSync(path)) core.setFailed('README.md nicht gefunden');

            let md = fs.readFileSync(path, 'utf8');
            const s = md.indexOf(start), e = md.indexOf(end);
            if (s === -1 || e === -1 || e < s) {
              core.setFailed(`Marker nicht gefunden: ${start} / ${end}`);
            } else {
              const updated = md.slice(0, s + start.length) + '\n' + process.env.PROJECTS + '\n' + md.slice(e);
              if (updated !== md) fs.writeFileSync(path, updated);
            }

      - name: Commit & Push
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update recent projects (daily)"
            git push
          fi
